const steps=[
 {img:'assets/market-reach-input.png',label:'STEP 01',title:'Simple farmer-friendly inputs',text:'The user provides a location, available margin capital and proposed business category. The interface stays intentionally simple and visual.',list:['Village / area / pincode','Available contribution capital','Business category']},
 {img:'assets/market-reach-loading.png',label:'STEP 02',title:'Samarth analyses the local area',text:'The system moves through a visible analysis flow — checking the local area, potential customers, existing businesses, demand signals and opportunities.',list:['Local area analysis','Potential customer discovery','Existing business signals','Demand & opportunity analysis']},
 {img:'assets/market-reach-dashboard.png',label:'STEP 03',title:'A decision-ready market dashboard',text:'The final view brings the local picture together: estimated customers, map-based reach, population distribution, demand indicators and distribution channels.',list:['5–10 km market view','Estimated customer base','Demand & distribution insights','Actionable local observations']}
];
const tabs=[...document.querySelectorAll('.demo-tab')],img=document.getElementById('demoImage'),label=document.getElementById('stepLabel'),title=document.getElementById('stepTitle'),text=document.getElementById('stepText'),list=document.getElementById('stepList'),next=document.getElementById('nextStep');let current=0;
function setStep(i){current=(i+3)%3;const s=steps[current];img.src=s.img;label.textContent=s.label;title.textContent=s.title;text.textContent=s.text;list.innerHTML=s.list.map(x=>`<li>${x}</li>`).join('');tabs.forEach((t,j)=>t.classList.toggle('active',j===current));next.textContent=current===2?'Back to input →':'Next stage →'}
tabs.forEach((t,i)=>t.addEventListener('click',()=>setStep(i)));next.addEventListener('click',()=>setStep(current+1));
const lb=document.getElementById('lightbox'),lbImg=document.getElementById('lightboxImg');document.getElementById('zoomBtn').addEventListener('click',()=>{lbImg.src=img.src;lb.classList.add('open');lb.setAttribute('aria-hidden','false')});document.getElementById('closeLightbox').addEventListener('click',()=>{lb.classList.remove('open');lb.setAttribute('aria-hidden','true')});lb.addEventListener('click',e=>{if(e.target===lb)lb.classList.remove('open')});
const menu=document.getElementById('menuBtn'),nav=document.getElementById('nav');menu.addEventListener('click',()=>nav.classList.toggle('open'));nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));
const back=document.getElementById('backTop');window.addEventListener('scroll',()=>back.classList.toggle('show',scrollY>700));back.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
setStep(0);
